In [1]:
from keras.utils import pad_sequences
import numpy as np
from keras.preprocessing.text import Tokenizer
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.neighbors import NearestNeighbors

In [29]:
data = np.random.rand(10, 1)
print(f'Data:\n{data}\n')

Data:
[[0.17681563]
 [0.39916614]
 [0.35175044]
 [0.37270024]
 [0.78567638]
 [0.74027608]
 [0.4999775 ]
 [0.41547649]
 [0.74392659]
 [0.22652596]]



In [31]:
nn = NearestNeighbors(n_neighbors=2,metric='euclidean',algorithm='kd_tree').fit(data)

euclidian, indices = nn.kneighbors((data))

print(f'Euclidian :\n{euclidian}\n')
print(f'Indices :\n{indices}')

Euclidian :
[[0.         0.04971032]
 [0.         0.01631034]
 [0.         0.0209498 ]
 [0.         0.0209498 ]
 [0.         0.04174979]
 [0.         0.0036505 ]
 [0.         0.08450101]
 [0.         0.01631034]
 [0.         0.0036505 ]
 [0.         0.04971032]]

Indices :
[[0 9]
 [1 7]
 [2 3]
 [3 2]
 [4 8]
 [5 8]
 [6 7]
 [7 1]
 [8 5]
 [9 0]]


In [6]:
np.sqrt([2.1074096945412923])

array([1.45169201])

In [16]:
print(np.argsort(distance))

[[0 1]
 [1 0]]


In [11]:
nn = np.array([[0,2,4,5], [0,2,4,5]])

for i in range(len(nn)):
    minority_neighbors = nn[i][nn[i] > 0]
    print(minority_neighbors)

[2 4 5]
[2 4 5]


In [32]:
myList = np.random.rand(5, 1)
print(myList)

[[0.97501375]
 [0.59749785]
 [0.75902118]
 [0.76445391]
 [0.89855471]]


In [36]:
euclidian = NearestNeighbors(n_neighbors=3,metric='euclidean',algorithm='kd_tree').fit(myList)
euclidians, indices = euclidian.kneighbors((myList))
# sorting = np.argsort(myList)[:, 1:4]
nn = []
for i in range(len(myList)):
    value = indices[i][indices[i] != i]
    nn.append(value)
nn = np.array(nn)
nn_random = np.random.choice(nn[0], size=1, replace=False)

print(f'Euclidian:\n{euclidians}\n')
print(f'Nearest Neighbors:\n {nn}\n')
print(f'NN Random:\n {nn_random}\n')

Euclidian:
[[0.         0.07645904 0.21055984]
 [0.         0.16152332 0.16695605]
 [0.         0.00543273 0.13953353]
 [0.         0.00543273 0.1341008 ]
 [0.         0.07645904 0.1341008 ]]

Nearest Neighbors:
 [[4 3]
 [2 3]
 [3 4]
 [2 4]
 [0 3]]

NN Random:
 [4]



In [99]:
myList[nn_random]

array([[1.35113743e-01, 6.09267393e-01, 6.22709791e-01, 6.91534164e-01,
        2.18420254e-01, 4.65407320e-01, 3.62377879e-01, 6.47611660e-01,
        2.49740468e-01, 6.41593535e-02, 5.07966735e-01, 5.07639607e-01,
        5.69292253e-01, 7.13151124e-01, 7.64996735e-01, 4.32178578e-01,
        1.79938853e-01, 4.59124528e-01, 8.33699137e-01, 6.86494574e-01,
        7.77568822e-01, 9.26335536e-01, 6.90084873e-01, 8.89187526e-01,
        6.72861356e-02, 5.04268773e-01, 6.72868867e-01, 6.22998023e-01,
        9.92241866e-01, 3.07932421e-01, 2.06899918e-01, 3.33327614e-01,
        5.25158094e-01, 5.95249675e-01, 2.60628258e-01, 2.41673415e-01,
        7.41107433e-01, 8.29871427e-01, 3.88801701e-01, 8.41898168e-01,
        9.52540361e-01, 8.91564434e-02, 7.05370041e-01, 1.73014564e-01,
        9.86008401e-01, 3.34154464e-01, 4.27048505e-01, 5.79073565e-01,
        8.41036034e-01, 3.22417955e-01, 2.94738539e-01, 1.21696649e-01,
        6.94894133e-01, 2.89831641e-01, 6.98030931e-01, 7.025948

In [ ]:
vector = np.random.rand(3,5)

In [ ]:
vector.shape

In [ ]:
# vector_random = np.random.rand(3,3)

# print(vector_random)

In [ ]:
vector_sequence = pad_sequences(vector, maxlen=10, padding='post', dtype=np.float64)

In [ ]:
vector_sequence

In [ ]:
kalimat = ['halo selamat siang']

In [ ]:
tokenizer = Tokenizer(num_words=40000, oov_token='OOV')

tokenizer.fit_on_texts(kalimat)

In [ ]:
for word, i in tokenizer.word_index.items():
    print(f'{word}: {i}')

In [ ]:
text = {'text': ['saya sedang makan', 'halo selamat sore']}
df = pd.DataFrame(text)

<h1>Back Propagation Code</h1>

In [ ]:
def backPropagation(self, x, y, learning_rate):
        T = len(x)
        dW_i, dU_i, db_i = np.zeros_like(self.W_i), np.zeros_like(self.U_i), np.zeros_like(self.b_i)
        dW_f, dU_f, db_f = np.zeros_like(self.W_f), np.zeros_like(self.U_f), np.zeros_like(self.b_f)
        dW_o, dU_o, db_o = np.zeros_like(self.W_o), np.zeros_like(self.U_o), np.zeros_like(self.b_o)
        dW_c, dU_c, db_c = np.zeros_like(self.W_c), np.zeros_like(self.U_c), np.zeros_like(self.b_c)
        dW_y, db_y = np.zeros_like(self.W_y), np.zeros_like(self.b_y)
        dc_next = np.zeros((1, self.hidden_size))
        dh_next = np.zeros((1, self.hidden_size))
        
        for t in reversed(range(T)):
            dy = self.outputs[t]
            # print(f'Outputs: {dy}\n')
            # print(f'{y[t]}\n')
            dy[y[t]] -= 1
            # print(f'Outputs minus 1{dy}\n')
            dy_transpose = dy.reshape(1, -1).T
            # print(f'Shape dy_transpose: {dy_transpose.shape}\n')
            # print(f'Shape self.W_y.T : {self.W_y.shape}\n')
            dh_forward = self.W_y.T @ dy_transpose + dh_next
            # print(f'Shape dh_forward: {dh_forward.shape}\n')
            dc_forward = dh_forward * self.gates_forward[t, 2] * tanh_derivative(tanh(self.c_forward[t + 1])) + dc_next
            dh_backward = self.W_y.T @ dy_transpose + dh_next
            dc_backward = dh_backward * self.gates_backward[t, 2] * tanh_derivative(tanh(self.c_backward[t + 1])) + dc_next
            
            # print(f'Shape dy_transpose: {dy_transpose.shape}\n')
            # print(f'Shape dW_y: {dW_y.shape}\n')
            # print(f'Shape self.h_forward: {self.h_forward[t + 1].shape}\n')
            # dW_y += dy_transpose @ np.expand_dims(self.h_forward[t + 1], axis=0) + dy_transpose @ np.expand_dims(self.h_backward[t + 1], axis=0) # Salah
            dW_y += dy_transpose @ np.expand_dims(np.concatenate([self.h_forward[t + 1], self.h_backward[t + 1][:self.hidden_size]]), axis=0) # Benar
            db_y += dy_transpose
            
            # print(f'dc_forward: {dc_forward.shape}, self.gates_forward[t, 3]: {self.gates_forward[t, 3].shape}\n')
            dg_forward = dc_forward * self.gates_forward[t, 2] * tanh_derivative(self.gates_forward[t, 3])
            dg_backward = dc_backward * self.gates_backward[t, 3]

            dgates_forward = self.gates_forward[t]
            # print(f'Shape dgates_forward[3]: {dgates_forward.shape}\n')
            # dg_forward_expanded = np.expand_dims(dg_forward, axis=0)
            dgated = dg_forward * tanh_derivative(dgates_forward[3])
            # print(f'tanh_derivative Shape: {dgated.shape}\n')
            # print(f'Shape dg_forward : {dg_forward.shape}')
            dgates_forward[3][:self.hidden_size] = np.sum(dg_forward[:self.hidden_size] * tanh_derivative(dgates_forward[3])[:self.hidden_size], axis=1) # Error disini
            dgates_forward[0][:self.hidden_size] = np.sum(dc_forward[:self.hidden_size] * self.gates_forward[t, 0], axis=1)
            dgates_forward[1][:self.hidden_size] = np.sum(dc_forward[:self.hidden_size] * self.c_forward[t], axis=1)
            dgates_forward[2][:self.hidden_size] = np.sum(dh_forward[:self.hidden_size] * tanh(self.c_forward[t + 1]) * sigmoid_derivative(dgates_forward[2]), axis=1)

            dgates_backward = self.gates_backward[t]
            dgates_backward[3][:self.hidden_size] = np.sum(dg_backward[:self.hidden_size] * tanh_derivative(dgates_backward[3]))
            dgates_backward[0][:self.hidden_size] = np.sum(dc_backward[:self.hidden_size] * self.gates_backward[t, 0])
            dgates_backward[1][:self.hidden_size] = np.sum(dc_backward[:self.hidden_size] * self.c_backward[t])
            dgates_backward[2][:self.hidden_size] = np.sum(dh_backward[:self.hidden_size] * tanh(self.c_backward[t + 1]) * sigmoid_derivative(dgates_backward[2]))
            
            x_transpose = np.array([x[t]])
            dgates_transpose_forward_0 = np.array([dgates_forward[0]])
            dgates_transpose_forward_1 = np.array([dgates_forward[1]])
            dgates_transpose_forward_2 = np.array([dgates_forward[2]])
            dgates_transpose_forward_3 = np.array([dgates_forward[3]])

            dgates_transpose_backward_0 = np.array([dgates_backward[0]])
            dgates_transpose_backward_1 = np.array([dgates_backward[1]])
            dgates_transpose_backward_2 = np.array([dgates_backward[2]])
            dgates_transpose_backward_3 = np.array([dgates_backward[3]])
            
            dW_i += dgates_transpose_forward_0.T @ x_transpose + dgates_transpose_backward_0.T @ x_transpose
            dU_i += dgates_forward[0] @ self.h_forward[t].T + dgates_backward[0] @ self.h_backward[t].T
            db_i += dgates_transpose_forward_0.T + dgates_transpose_backward_0.T
            
            dW_f += dgates_transpose_forward_1.T @ x_transpose + dgates_transpose_backward_1.T @ x_transpose # Error disini
            dU_f += dgates_forward[1] @ self.h_forward[t].T + dgates_backward[1] @ self.h_backward[t].T
            db_f += dgates_transpose_forward_1.T + dgates_transpose_backward_1.T
            
            dW_o += dgates_transpose_forward_2.T @ x_transpose + dgates_transpose_backward_2.T @ x_transpose
            dU_o += dgates_forward[2] @ self.h_forward[t].T + dgates_backward[2] @ self.h_backward[t].T
            db_o += dgates_transpose_forward_2.T + dgates_transpose_backward_2.T
            
            dW_c += dgates_transpose_forward_3.T @ x_transpose + dgates_transpose_backward_3.T @ x_transpose
            dU_c += dgates_forward[3] @ self.h_forward[t].T + dgates_backward[3] @ self.h_backward[t].T
            db_c += dgates_transpose_forward_3.T + dgates_transpose_backward_3.T
            
            dh_next = self.U_i.T @ dgates_forward[0] + self.U_f.T @ dgates_forward[1] + self.U_o.T @ dgates_forward[2] + self.U_c.T @ dgates_forward[3]
            dc_next = dc_forward * self.gates_forward[t, 1]
        
        for param in [dW_i, dU_i, db_i, dW_f, dU_f, db_f, dW_o, dU_o, db_o, dW_c, dU_c, db_c, dW_y, db_y]:
            np.clip(param, -1, 1, out=param)
        
        self.W_i -= learning_rate * dW_i
        self.U_i -= learning_rate * dU_i
        self.b_i -= learning_rate * db_i
        
        self.W_f -= learning_rate * dW_f
        self.U_f -= learning_rate * dU_f
        self.b_f -= learning_rate * db_f
        
        self.W_o -= learning_rate * dW_o
        self.U_o -= learning_rate * dU_o
        self.b_o -= learning_rate * db_o
        
        self.W_c -= learning_rate * dW_c
        self.U_c -= learning_rate * dU_c
        self.b_c -= learning_rate * db_c
        
        self.W_y -= learning_rate * dW_y
        self.b_y -= learning_rate * db_y