In [1]:
import numpy as np
import pandas as pd
import dataframe_image as dfi
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

<h1>Read Datasets<h1>

In [2]:
df = pd.read_excel('Datasets_Ready.xlsx')

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4510 entries, 0 to 4509
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      4510 non-null   int64  
 1   Text            4510 non-null   object 
 2   emoji           4510 non-null   object 
 3   Tokenized       4510 non-null   object 
 4   final_text      4494 non-null   object 
 5   text_emoji      4510 non-null   object 
 6   Pos_Word        4510 non-null   int64  
 7   Neg_Word        4510 non-null   int64  
 8   Total_Word      4510 non-null   int64  
 9   Pos_Ratio       4510 non-null   float64
 10  Neg_Ratio       4510 non-null   float64
 11  Sentimen_Text   4510 non-null   object 
 12  Tokenize_Emoji  4510 non-null   object 
 13  Pos_Emoji       4510 non-null   int64  
 14  Neg_Emoji       4510 non-null   int64  
 15  Sentimen_Emoji  4510 non-null   object 
 16  Sarcasm         4510 non-null   object 
dtypes: float64(2), int64(6), object(9

Unnamed: 0                                               Text  \
0           0         kawan2 sunda bersatu jemput arteria dahlan   
1           2  arteria dahlan disidang adat sunda daerah menu...   
2           4  ga ditafsirkan membanding bandingkan edy arter...   
3           5  nantik ngak divhumas polri nya bilang palsu td...   
4           6  urut dada dech kuasa hukum tdk mengerti hukum ...   

                           emoji  \
0                              😁   
1                              😁   
2                              😁   
3                              😁   
4                              😁   

                                           Tokenized  \
0  ['kawan', 'sunda', 'bersatu', 'jemput', 'arter...   
1  ['arteria', 'dahlan', 'sidang', 'adat', 'sunda...   
2  ['ga', 'tafsir', 'membanding', 'membandingkan'...   
3  ['nanti', 'tidak', 'divisi humas', 'polri', '....   
4  ['urut', 'dada', 'deh', 'kuasa', 'hukum', 'tid...   

                                          final_text  \
0          kawan sunda bersatu jemput arteria dahlan   
1  arteria dahlan sidang adat sunda daerah menunt...   
2  ga tafsir membanding membandingkan edy arteria...   
3  divisi humas polri bilang palsu mengeluarkan a...   
4  urut dada deh kuasa hukum mengerti hukum arter...   

                                          text_emoji  Pos_Word  Neg_Word  \
0        kawan sunda bersatu jemput arteria dahlan 😁         2         0   
1  arteria dahlan sidang adat sunda daerah menunt...         5         4   
2  ga tafsir membanding membandingkan edy arteria...         3         2   
3  divisi humas polri bilang palsu mengeluarkan a...         4         8   
4  urut dada deh kuasa hukum mengerti hukum arter...        14         6   

   Total_Word  Pos_Ratio  Neg_Ratio Sentimen_Text  \
0           6   0.333333   0.000000       Positif   
1           9   0.555556   0.444444       Positif   
2           9   0.333333   0.222222       Positif   
3          16   0.250000   0.500000       Negatif   
4          28   0.500000   0.214286       Positif   

                                      Tokenize_Emoji  Pos_Emoji  Neg_Emoji  \
0  ['kawan', 'sunda', 'bersatu', 'jemput', 'arter...          1          0   
1  ['arteria', 'dahlan', 'sidang', 'adat', 'sunda...          1          0   
2  ['ga', 'tafsir', 'membanding', 'membandingkan'...          1          0   
3  ['divisi', 'humas', 'polri', 'bilang', 'palsu'...          1          0   
4  ['urut', 'dada', 'deh', 'kuasa', 'hukum', 'men...          1          0   

  Sentimen_Emoji  Sarcasm  
0        Positif  Negatif  
1        Positif  Negatif  
2        Positif  Negatif  
3        Positif  Positif  
4        Positif  Negatif

In [3]:
# Remove unused column/feature
df = df.drop(columns='Unnamed: 0')
df = df.drop(columns='Text')
df = df.drop(columns='emoji')
df = df.drop(columns='Tokenized')
df = df.drop(columns='final_text')
df = df.drop(columns='Pos_Word')
df = df.drop(columns='Neg_Word')
df = df.drop(columns='Total_Word')
df = df.drop(columns='Pos_Ratio')
df = df.drop(columns='Neg_Ratio')
df = df.drop(columns='Tokenize_Emoji')
df = df.drop(columns='Pos_Emoji')
df = df.drop(columns='Neg_Emoji')
df = df.drop(columns='Sentimen_Emoji')

In [4]:
df.head()

text_emoji Sentimen_Text  Sarcasm
0        kawan sunda bersatu jemput arteria dahlan 😁       Positif  Negatif
1  arteria dahlan sidang adat sunda daerah menunt...       Positif  Negatif
2  ga tafsir membanding membandingkan edy arteria...       Positif  Negatif
3  divisi humas polri bilang palsu mengeluarkan a...       Negatif  Positif
4  urut dada deh kuasa hukum mengerti hukum arter...       Positif  Negatif

<h1>Checking Max Length In Every Record</h1>

In [5]:
df['token'] = df['text_emoji'].apply(lambda x: x.split())

In [6]:
df['max_words'] = df['token'].apply(lambda x: len(x))

In [7]:
df['max_words'].describe()

count    4510.000000
mean       11.484922
std         6.464542
min         1.000000
25%         7.000000
50%        10.000000
75%        15.000000
max        39.000000
Name: max_words, dtype: float64

In [8]:
df = df.drop(columns=['token', 'max_words'])

In [9]:
print(f'Total Duplicated Data: {df.duplicated().sum()}')

Total Duplicated Data: 120


In [10]:
df.loc[df.duplicated(), :]

text_emoji Sentimen_Text  Sarcasm
23    acara resmi pakai bahasa indonesia tp penyelen...       Negatif  Positif
852       contoh firaun suka menginjak harkat pribumi 😨       Negatif  Negatif
853       contoh firaun suka menginjak harkat pribumi 😨       Negatif  Negatif
859            opini cak nun kafir haman qorun suroto 😨       Negatif  Negatif
888   andre menilai pernyataan cak nun prabowo subia...       Negatif  Negatif
...                                                 ...           ...      ...
4421                drakor pencitraan mengalihkan isu 💯       Positif  Negatif
4426                                 kerja pencitraan 💯       Negatif  Positif
4505                                                  😭       Positif  Positif
4506                                      gelandangan 😭       Negatif  Negatif
4508                                          bangsat 😭       Negatif  Negatif

[120 rows x 3 columns]

In [11]:
df = df.drop_duplicates(ignore_index = True)

In [12]:
df.head()

text_emoji Sentimen_Text  Sarcasm
0        kawan sunda bersatu jemput arteria dahlan 😁       Positif  Negatif
1  arteria dahlan sidang adat sunda daerah menunt...       Positif  Negatif
2  ga tafsir membanding membandingkan edy arteria...       Positif  Negatif
3  divisi humas polri bilang palsu mengeluarkan a...       Negatif  Positif
4  urut dada deh kuasa hukum mengerti hukum arter...       Positif  Negatif

In [13]:
print(f'Total Duplicated Data After Handling: {df.duplicated().sum()}')

Total Duplicated Data After Handling: 0


In [ ]:
# df_duplicated = pd.DataFrame(df.loc[df['text_emoji'].duplicated()])

In [ ]:
# df_duplicated.to_excel('Duplicated_Data.xlsx')

In [14]:
print(f'Total Missing Value: \n{df.isnull().sum()}')

Total Missing Value: 
text_emoji       0
Sentimen_Text    0
Sarcasm          0
dtype: int64


<h1>Feature Extraction Using GloVe Method</h1>

In [ ]:
class GloVe:
    # constructors
    def __init__(self, corpus, embedding_size, window_size=5):
        self.corpus = corpus
        self.embedding_size = embedding_size
        self.window_size = window_size
        self.word2id = {}
        self.id2word = {}
        self.word2count = {}
        self.vocab_size = 0
        self.co_matrix = None
        self.embedding = None
        self.bias = None

    def build_vocab_information(self):
        for sentence in self.corpus:
            for word in sentence.split():
                if word not in self.word2id:
                    self.word2id[word] = self.vocab_size
                    self.id2word[self.vocab_size] = word
                    self.vocab_size += 1
                self.word2count[word] = self.word2count.get(word, 0) + 1
        print(f'Vocab Size: {self.vocab_size}')

    def build_co_matrix(self):
        self.co_matrix = np.zeros((self.vocab_size, self.vocab_size))
        for sentence in self.corpus:
            sentence = sentence.split()
            for i, center_word in enumerate(sentence):
                for j in range(max(0, i - self.window_size), i):
                    context_word = sentence[j]
                    self.co_matrix[self.word2id[center_word]][self.word2id[context_word]] += 1
                    self.co_matrix[self.word2id[context_word]][self.word2id[center_word]] += 1

    def train(self, num_epochs=100, learning_rate=0.01):
        self.embedding = (np.random.rand(self.vocab_size, self.embedding_size) - 0.5) / self.embedding_size
        self.bias = np.zeros(self.vocab_size)
        count = 0
        for epoch in range(num_epochs):
            count += 1
            loss = 0
            for i in range(self.vocab_size):
                for j in range(self.vocab_size):
                    if self.co_matrix[i][j] != 0:
                        diff = (self.embedding[i] @ self.embedding[j]) + self.bias[i] + self.bias[j] - np.log(self.co_matrix[i][j])
                        
                        loss += diff ** 2
                        
                        grad_emb_i = diff * self.embedding[j]
                        grad_emb_j = diff * self.embedding[i]
                        
                        grad_bias_i = diff
                        grad_bias_j = diff

                        self.embedding[i] -= learning_rate * grad_emb_i
                        self.embedding[j] -= learning_rate * grad_emb_j
                        self.bias[i] -= learning_rate * grad_bias_i
                        self.bias[j] -= learning_rate * grad_bias_j
                        
            print(f'Difference Iterasi {count}: {diff}\n')
            print(f'Loss Iterasi {count}: {loss}\n')
            print(f'Gradient Embedding "i" Iterasi {count}: {grad_emb_i}\n')
            print(f'Gradient Embedding "j" Iterasi {count}: {grad_emb_j}\n')
            print(f'Embedding Iterasi {count}: {self.embedding}')

            print(f'Epoch {epoch + 1}/{num_epochs} - loss {round(loss, 3)}')
            
            if loss <= 0.001:
                print('Training Stopped, loss less than equal 0.001')
                break

    def get_all_embeddings(self):
        all_embeddings = {}
        for word, word_id in self.word2id.items():
            all_embeddings[word] = self.embedding[word_id]
        return all_embeddings
    
    def get_embeddings_by_id(self, id):
        return self.embedding[id]
    
    def get_embeddings(self, kata):
        word_embeddings = {}
        for word, word_id in self.word2id.items():
            if word == kata:
                word_embeddings[word] = self.embedding[word_id]
        return word_embeddings

    def embedding2word(self):
        embedding_to_word = {}
        for word, word_id in self.word2id.items():
            embedding_to_word[tuple(self.embedding[word_id])] = word
        return embedding_to_word
    
    def get_glove_embedding(self, sentence):
        sentence = sentence.split()
        embedding_vectors = []
        for word in sentence:
            if word in self.word2id:
                word_id = self.word2id[word]
                word_embedding = self.embedding[word_id]
                embedding_vectors.append(word_embedding)
        return embedding_vectors
    
    def show_comatrix(self):
        # df_co_matrix = pd.DataFrame(self.co_matrix, index=self.word2id.keys(), columns=self.word2id.keys())
        
        return self.co_matrix
    
    def generate_coomatrix_image(self):
        df_co_matrix = pd.DataFrame(self.co_matrix, index=self.word2id.keys(), columns=self.word2id.keys())

        print('Image is being processed...')
        dfi.export(df_co_matrix.head(10), "coocurrenceMatrixBab3.png", max_cols=10)
        
        return print('Coocurrence matrix has been successfully generated into an image')
    
    def show_word2id(self):
        return self.word2id
    
    def show_id2word(self):
        return self.id2word
    
    def show_word2count(self):
        return self.word2count

In [ ]:
# Membangun model GloVe
embedding_size = 50

glove_model = GloVe(df['text_emoji'], embedding_size)

# Membangun vocabulary
glove_model.build_vocab_information()

# Membangun co-occurrence matrix
glove_model.build_co_matrix()

# Melatih model GloVe
glove_model.train()

In [ ]:
# Menampilkan Dict word2id
word_2_id = glove_model.show_word2id()
word_2_id

In [ ]:
# Menampilkan Dict id2word
id_2_word = glove_model.show_id2word()
id_2_word

In [ ]:
# Menampilkan Dict word2count
word_2_count = glove_model.show_word2count()
word_2_count

In [ ]:
# Menampilkan hasil dari Cooccurence Matrix
co_matrix = glove_model.show_comatrix()

co_matrix

In [ ]:
# # Generate image Matrix Coocurrence
# generateCooMatrix = glove_model.generate_coomatrix_image()

# generateCooMatrix

In [ ]:
word_embeddings = glove_model.get_embeddings('😁')

print(word_embeddings)

In [ ]:
embedding_by_id = glove_model.get_embeddings_by_id(6)

embedding_by_id

In [ ]:
all_embedding = glove_model.get_all_embeddings()

all_embedding['kawan']

In [ ]:
# # Menyimpan embedding ke file teks

# embeddings = glove_model.get_all_embeddings()

# output_file = "Misc/Embeddings/embeddings50D.txt"
# with open(output_file, "w", encoding="utf-8") as file:
#     for word, embedding in embeddings.items():
#         embedding_line = "{} {}\n".format(word, " ".join(str(value) for value in embedding))
#         file.write(embedding_line)

# print("Embedding telah berhasil disimpan ke: {}".format(output_file))

<h1>Create New Feature for Word Embeddings</h1>

In [ ]:
# df_ready['embedding'] = df_ready['text_emoji'].apply(lambda x: glove_model.get_glove_embedding(x))

In [ ]:
# df_ready.head()

<h2>Fungsi untuk merubah token menjadi representasi word embedding</h2>

In [ ]:
def replace_token_with_word_embedding(text):
    embeddings = []
    for word in text.split():
        if word in all_embedding:
            embeddings.append(all_embedding[word])
    
    return np.array(embeddings)

In [ ]:
kalimat = df['text_emoji'][0]
output = []

for sentence in kalimat.split():
    if sentence in all_embedding:
        output.append(all_embedding[sentence])
    
print(len(np.array(output)))

In [ ]:
df['vector'] = df['text_emoji'].apply(replace_token_with_word_embedding)

In [ ]:
df.head()

In [ ]:
# df_ready['text_emoji'].duplicated().sum()

In [ ]:
# df_ready.head()

In [ ]:
# df_ready['text_emoji'][0]

In [ ]:
# embedding2word = glove_model.embedding2word()

# embedding2word[tuple(df_ready['text_emoji'][0][0])]

<h1>Implement SMOTE</h1>

In [15]:
df['Sentimen_Text'] = df['Sentimen_Text'].replace('Positif', 1)
df['Sentimen_Text'] = df['Sentimen_Text'].replace('Negatif', 0)

df['Sarcasm'] = df['Sarcasm'].replace('Positif', 1)
df['Sarcasm'] = df['Sarcasm'].replace('Negatif', 0)

In [16]:
X = np.array(df['text_emoji'])
y = np.array(df['Sarcasm'])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [ ]:
# Cek class minoritas
print(f'Total Sample for each class:\n{y_train.value_counts()}')

<p>Terlihat Bahwa class minoritas adalah class dengan nilai 1(Positif)</p>

In [ ]:
y_train

In [ ]:
np.where(y_train == 1)[0]

In [ ]:
X_train[np.where(y_train == 1)[0]]

In [18]:
max_len = 39
len_voc = 40000

In [ ]:
df_train_min = X_train[np.where(y_train == 1)[0]]
df_train_maj = X_train[np.where(y_train == 0)[0]]

df_test = X_test

In [ ]:
df_train_min

In [ ]:
new_arrays_train_min = []

for i in df_train_min:
    new_array = np.delete(i, -1)
    new_arrays_train_min.append(new_array)

df_train_min_text = np.concatenate(new_arrays_train_min)

In [ ]:
df_train_min_text

In [ ]:
new_arrays_train_maj = []

for i in df_train_maj:
    new_array = np.delete(i, -1)
    new_arrays_train_maj.append(new_array)

df_train_maj_text = np.concatenate(new_arrays_train_maj)

In [ ]:
new_arrays_test = []

for i in df_test:
    new_array = np.delete(i, -1)
    new_arrays_test.append(new_array)

df_test_text = np.concatenate(new_arrays_test)

In [ ]:
len(df_train_min_text)

In [ ]:
len(df_train_maj_text)

In [ ]:
len(df_test_text)

In [ ]:
# df_ready_min = pd.concat([df_train_min, df_test_min])
# df_ready_maj = pd.concat([df_train_maj, df_test_maj])

In [19]:
# Tokenizing
def make_tokenizer(texts, len_voc):
    from keras.preprocessing.text import Tokenizer
    t = Tokenizer(num_words=len_voc)
    t.fit_on_texts(texts)
    
    return t

<h2>Tokenizer</h2>

In [20]:
tokenizer = make_tokenizer(X_train, len_voc)

In [21]:
tokenizer_test = make_tokenizer(X_test, len_voc)

In [ ]:
tokenizer_train_min = make_tokenizer(df_train_min_text, len_voc)
tokenizer_train_maj = make_tokenizer(df_train_maj_text, len_voc)
tokenizer_test = make_tokenizer(df_test_text, len_voc)

In [ ]:
tokenizer_train_min.word_index

<h2>Sequence</h2>

In [22]:
X_train_Sequence = tokenizer.texts_to_sequences(X_train)

In [23]:
X_test_Sequence = tokenizer_test.texts_to_sequences(X_test)

In [ ]:
X_train_min = tokenizer_train_min.texts_to_sequences(df_train_min_text)
X_train_major = tokenizer_train_maj.texts_to_sequences(df_train_maj_text)
X_test = tokenizer_test.texts_to_sequences(df_test_text)

# X_train_Sentiment = df_train['Sentimen_Text']
# X_test_Sentiment = df_test['Sentimen_Text']

In [ ]:
X_train_min

In [ ]:
X_train_major

<h2>Padding</h2>

In [24]:
from keras.utils import pad_sequences

X_train_Padded = pad_sequences(X_train_Sequence, maxlen=max_len, padding='post', truncating='post')

In [25]:
X_test_Padded = pad_sequences(X_test_Sequence, maxlen=max_len, padding='post', truncating='post')

In [ ]:
from keras.utils import pad_sequences

X_train_min = pad_sequences(X_train_min, maxlen=max_len, padding='post', truncating='post')
X_train_major = pad_sequences(X_train_major, maxlen=max_len, padding='post', truncating='post')
X_test = pad_sequences(X_test, maxlen=max_len, padding='post', truncating='post')

In [ ]:
X_train_min

<h2>Stacking Label Minority</h2>

In [ ]:
y_train_min = y_train[np.where(y_train == 1)[0]]

In [ ]:
y_train_min.shape

<h2>Stacking Label Majority</h2>

In [ ]:
y_train_maj = y_train[np.where(y_train == 0)[0]]

In [ ]:
y_train_maj.shape

<h2>Stacking Sentiment Minority</h2>

In [ ]:
X_train_sentiment_min = []
for i in range(len(df_train_min)):
    X_train_sentiment_min.append(df_train_min[i][1])

X_train_sentiment_min = np.array(X_train_sentiment_min)

In [ ]:
X_train_sentiment_min = X_train_sentiment_min.reshape(X_train_sentiment_min.shape[0], 1)

In [ ]:
X_train_sentiment_min

In [ ]:
X_train_sentiment_min.shape

<h2>Stacking Sentiment Majority</h2>

In [ ]:
X_train_sentiment_maj = []
for i in range(len(df_train_maj)):
    X_train_sentiment_maj.append(df_train_maj[i][1])

X_train_sentiment_maj = np.array(X_train_sentiment_maj)

In [ ]:
X_train_sentiment_maj = X_train_sentiment_maj.reshape(X_train_sentiment_maj.shape[0], 1)

In [ ]:
X_train_sentiment_maj

In [ ]:
X_train_sentiment_maj.shape

<h2>Stacking Sentiment Testing</h2>

In [ ]:
X_test_sentiment = []
for i in range(len(df_test)):
    X_test_sentiment.append(df_test[i][1])

X_test_sentiment = np.array(X_test_sentiment)

In [ ]:
X_test_sentiment = X_test_sentiment.reshape(X_test_sentiment.shape[0], 1)

In [ ]:
X_test_sentiment

In [ ]:
X_test_sentiment.shape

In [26]:
def get_coefs(word,*arr): 
    return word, np.asarray(arr, dtype='float32')

def load_embedding(file):
    embeddings_index = dict(get_coefs(*i.split(" ")) for i in open(file, encoding='utf-8'))
    
    return embeddings_index

In [27]:
def make_embedding_matrix(embedding, tokenizer, len_voc):
    all_embs = np.stack(embedding.values())
    emb_mean,emb_std = all_embs.mean(), all_embs.std()
    embed_size = all_embs.shape[1]
    word_index = tokenizer.word_index
    embedding_matrix = np.random.normal(emb_mean, emb_std, (len_voc, embed_size))
    # embedding_matrix = np.zeros((len_voc, embed_size))
    
    for word, i in word_index.items():
        if i >= len_voc:
            continue
        embedding_vector = embedding.get(word)
        if embedding_vector is not None: 
            embedding_matrix[i] = embedding_vector
    
    return embedding_matrix

In [28]:
glove = load_embedding('Misc/Embeddings/embeddings100D.txt')

In [29]:
glove.get('foto')

array([-0.1664963 , -0.1963187 , -0.1384915 , -0.11371673,  0.0414871 ,
       -0.11432921,  0.10378131, -0.03174866,  0.05559847,  0.24566665,
        0.04883485,  0.16087544,  0.04765552,  0.0860668 , -0.1036344 ,
       -0.10560928, -0.05109665, -0.01595475, -0.11956628,  0.1289334 ,
       -0.19900735, -0.04745169, -0.05132945,  0.0320598 ,  0.03187682,
       -0.07786787, -0.14429773,  0.23841153, -0.26779142,  0.09531006,
       -0.12839785,  0.0138438 ,  0.05771478, -0.06913733,  0.2861561 ,
        0.08038941,  0.0523537 ,  0.07629201,  0.05946291,  0.1258838 ,
       -0.00635946,  0.0659649 , -0.00871249,  0.01503011, -0.02720634,
        0.1058095 , -0.16123803, -0.15095785, -0.3382308 , -0.19761616,
       -0.23972012,  0.16163072,  0.01586286,  0.07370322, -0.17882337,
        0.02930516, -0.26223096,  0.23496465,  0.04109401,  0.01506277,
       -0.05834723, -0.00463794, -0.23533121, -0.02478273, -0.00846084,
       -0.20255427,  0.02095671,  0.22667049, -0.19158429, -0.06

In [30]:
embed_matrix = make_embedding_matrix(glove, tokenizer, len_voc)

C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3378: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [31]:
X_train_embedding = embed_matrix[X_train_Padded]

In [32]:
embed_matrix_test = make_embedding_matrix(glove, tokenizer_test, len_voc)

X_test_embedding = embed_matrix_test[X_test_Padded]

In [33]:
train_size, max_len, embed_size = X_train_embedding.shape
X_train_embedding_r = X_train_embedding.reshape(train_size, max_len*embed_size)

test_size, max_len, embed_size = X_test_embedding.shape
X_test_embedding_r = X_test_embedding.reshape(test_size, max_len*embed_size)

In [34]:
smote = SMOTE()

X_oversampled, y_oversampled = smote.fit_resample(X_train_embedding_r, y_train)

In [35]:
unique_values, value_counts = np.unique(y_oversampled, return_counts=True)

for value, counts in zip(unique_values, value_counts):
    print(f'{value}: {counts}')

0: 2012
1: 2012


In [ ]:
embed_mat_train_min = make_embedding_matrix(glove, tokenizer_train_min, len_voc)
embed_mat_train_maj = make_embedding_matrix(glove, tokenizer_train_maj, len_voc)

embed_mat_test = make_embedding_matrix(glove, tokenizer_test, len_voc)

In [ ]:
embed_mat_train_min.shape

In [ ]:
X_train_emb_minority = embed_mat_train_min[X_train_min]
X_train_emb_majority = embed_mat_train_maj[X_train_major]

X_test_emb = embed_mat_test[X_test]

In [ ]:
X_train_emb_minority

In [ ]:
train_size_min, max_len_min, embed_size_min = X_train_emb_minority.shape
X_train_emb_r_min = X_train_emb_minority.reshape(train_size_min, max_len*embed_size_min)

train_size_maj, max_len_maj, embed_size_maj = X_train_emb_majority.shape
X_train_emb_r_maj = X_train_emb_majority.reshape(train_size_maj, max_len*embed_size_maj)

In [ ]:
X_train_emb_r_min.shape

In [ ]:
X_train_emb_r_maj.shape

In [ ]:
test_size, max_len, embed_size = X_test_emb.shape
X_test_emb_r = X_test_emb.reshape(test_size, max_len*embed_size)

In [ ]:
X_test_emb_r.shape

<h2>Stacking All Data Minority & Majority</h2>

In [ ]:
stack_train_minority = np.hstack((X_train_emb_r_min, X_train_sentiment_min))
stack_train_majority = np.hstack((X_train_emb_r_maj, X_train_sentiment_maj))

stack_testing = np.hstack((X_test_emb_r, X_test_sentiment))

In [ ]:
print(f'Shape stack minority: {stack_train_minority.shape}')
print(f'Shape stack majority: {stack_train_majority.shape}')

In [ ]:
# test_size, max_len, embed_size = X_test_emb.shape
# X_test_emb_r = X_test_emb.reshape(test_size, max_len*embed_size)

In [ ]:
# X = df_ready['embedding']
# X_sentiment = np.array(df_ready['Sentimen_Text']).reshape(-1, 1)
# y = np.array(df_ready['Sarcasm'])

In [ ]:
# from sklearn.model_selection import train_test_split
# # Bagi dataset menjadi train set dan test set
# X_train, X_test, X_sentiment_train, X_sentiment_test, y_train, y_test = train_test_split(X, X_sentiment, y, test_size=0.4, random_state=42)

In [ ]:
# X_minority = X_train[y_train == 1]
# X_sentiment_minority = X_sentiment_train[y_train == 1]
# y_minority = y_train[y_train == 1]

In [ ]:
# len(X_minority)

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

def euclidean_distance(X1, X2):
    return euclidean_distances(X1, X2)

def get_neighbors(distances, k):
    return np.argsort(distances)[:, 1:k+1]

def generate_synthetic_samples(X_minority, neighbors, k_neighbors):
    synthetic_samples = []

    for i in range(len(X_minority)):
        minority_neighbors = neighbors[i][neighbors[i] < len(X_minority)]
        nn = np.random.choice(minority_neighbors, size=min(k_neighbors, len(minority_neighbors)), replace=False)
        alpha = np.random.uniform(0, 1)
        synthetic_sample = X_minority[i] + alpha * (X_minority[nn] - X_minority[i])
        
        if synthetic_sample.size > 1:
            synthetic_sample = synthetic_sample[:1]

        print(synthetic_sample)
        
        synthetic_samples.append(synthetic_sample)

    data_synthetic = np.vstack(synthetic_samples)
    for i in range(len(synthetic_samples)):
        print(synthetic_samples[i].shape)
    return data_synthetic

def smote(X_minority, X_majority, y_minority, k):
    minority_size = X_minority.shape[0]
    majority_size = X_majority.shape[0]  # Asumsi jumlah sampel mayoritas sama dengan jumlah sampel minoritas
    
    # Menghitung jumlah tetangga terdekat berdasarkan perbandingan antara jumlah sampel minoritas dan mayoritas
    k_neighbors = int((majority_size / minority_size) * k)
    
    if k_neighbors > k:
        k_neighbors = k

    # Menghitung jarak antara sampel minoritas dan mayoritas
    distances = euclidean_distance(X_minority, X_majority)
    print('Distance\n')
    print(f'{distances}\n')
    
    # Mendapatkan tetangga terdekat untuk setiap sampel minoritas
    neighbors = get_neighbors(distances, k_neighbors)
    print('Neighbors\n')
    print(f'{neighbors}\n')
    print(f'Length : {neighbors.shape[0]}\n')
    
    # Menghasilkan sampel sintetis
    print('Synthetic Data\n')
    synthetic_samples = generate_synthetic_samples(X_minority, neighbors, k_neighbors)
    synthetic_labels = np.ones(len(synthetic_samples))
    
    # Menggabungkan sampel minoritas asli dengan sampel sintetis
    X_oversampled = np.vstack((X_minority, synthetic_samples))
    y_oversampled = np.hstack((y_minority, synthetic_labels))
    
    return X_oversampled, y_oversampled

In [ ]:
total_size = train_size_maj + train_size_min + test_size

In [ ]:
# Menjalankan SMOTE pada data stack
X_minority = stack_train_minority
y_minority = y_train_min
X_majority = stack_train_minority
y_majority = y_train_maj

X_oversampled, y_oversampled = smote(X_minority, X_majority, y_minority, k=5)

# Memisahkan kembali data menjadi train dan test set
X_train_oversampled = X_oversampled[:total_size]
X_test_oversampled = X_oversampled[total_size:]

y_train_oversampled = y_oversampled[:total_size]
y_test_oversampled = y_oversampled[total_size:]

In [ ]:
final_stack = np.vstack((stack_train_majority, X_oversampled))

In [ ]:
len(final_stack)

In [ ]:
final_stack = np.delete(final_stack, np.s_[4024::], axis=0)

In [ ]:
final_stack.shape

In [ ]:
final_stack_label = np.hstack((y_train_maj, y_oversampled))

In [ ]:
final_stack_label = np.delete(final_stack_label, np.s_[4024::], axis=0)

In [ ]:
print(f'Final Shape Data: {final_stack.shape}\n')

In [ ]:
print(f'Final Shape Label: {final_stack_label.shape}\n')

In [ ]:
# Menghitung Jumlah Akhir Sample pada Class 0 dan 1
unique, counts = np.unique(final_stack_label, return_counts=True)
result = np.asarray((unique, counts)).T.astype(int)

print(result[0][1])

In [ ]:
import matplotlib.pyplot as plt

x = ['Sebelum', 'Sesudah']
y = [len(X_train_emb_r_min) + len(X_train_emb_r_maj), len(final_stack)]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Perbandingan Data Training Setelah Diimplementasi SMOTE')

plt.show()

In [ ]:
x = ['0', '1']
y = [1794, 1718]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Jumlah Sample Masing-Masing Kelas Pada Data Training Sebelum Di Implementasi SMOTE')

plt.show()

In [ ]:
x = ['0', '1']
y = [result[0][1], result[1][1]]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Jumlah Sample Masing-Masing Kelas Setelah Di Implementasi SMOTE')

plt.show()

In [ ]:
# X_embedding = np.array(df_ready['embedding'][:2]).reshape(-1, 1)
# sentiment_values = np.array(df_ready['Sentimen_Text'][:2]).reshape(-1, 1)

# num_rows = X_embedding.shape[0]

# X_sentiment = np.empty((num_rows, 1), dtype=np.str_)

# for i in range(num_rows):
#     X_sentiment[i] = sentiment_values[i % sentiment_values.shape[0]]

# X = np.hstack((X_embedding, X_sentiment))

# X

In [ ]:
# y = df_ready['Sarcasm']

# y

In [ ]:
# from sklearn.neighbors import NearestNeighbors

# def get_k_nearest_neighbors(X, sample, k):
#     # Mencari tetangga terdekat menggunakan k-NN
#     knn = NearestNeighbors(n_neighbors=k+1)
#     knn.fit(X)
    
#     # Mengembalikan indeks tetangga terdekat untuk sampel
#     _, indices = knn.kneighbors([sample])
#     indices_1d = indices.flatten()  # Mengubah menjadi 1D array
    
#     return indices_1d[1:]  # Menghilangkan indeks diri sendiri

In [ ]:
# import pandas as pd
# import numpy as np
# import math

# def SMOTE(df, k, oversampling_ratio):
#     # Mendapatkan array numpy dari fitur embedding, sentiment, dan label
#     embeddings = np.vstack(df['embedding'].to_numpy())
#     labels = df['Sarcasm'].to_numpy()
    
#     # Menginisialisasi array untuk menyimpan sampel sintetis yang dihasilkan
#     synthetic_samples = []
    
#     # Mencari indeks sampel minoritas dan mayoritas
#     minority_indices = np.where(labels == 1)[0]
#     majority_indices = np.where(labels == 0)[0]
    
#     # Menghitung jumlah sampel sintetis yang akan dibuat untuk kelas minoritas
#     num_minority_samples = len(minority_indices)
#     num_majority_samples = len(majority_indices)
    
#     num_synthetic_samples = min(num_majority_samples - num_minority_samples, math.ceil(num_minority_samples * oversampling_ratio))
    
#     if num_synthetic_samples <= 0:
#         return pd.DataFrame()  # Return empty DataFrame jika tidak ada sampel sintetis yang perlu dibuat
    
#     # Looping melalui setiap sampel minoritas
#     for i in minority_indices:
#         sample = embeddings[i]
        
#         # Mencari tetangga terdekat untuk sampel minoritas
#         neighbors = get_k_nearest_neighbors(embeddings, sample, k)
        
#         # Menghasilkan sampel sintetis
#         for j in range(num_synthetic_samples):
#             # Memilih satu tetangga acak
#             neighbor_index = np.random.choice(neighbors)
            
#             if neighbor_index >= len(embeddings):
#                 continue  # Skip jika indeks tetangga melebihi ukuran data yang valid
            
#             neighbor = embeddings[neighbor_index]
            
#             # Menghitung selisih antara sampel dan tetangga
#             diff = neighbor - sample
            
#             # Menghasilkan sampel sintetis dengan proporsi acak
#             proportion = np.random.uniform(0, 1, size=1)
#             synthetic_sample = sample + proportion * diff
            
#             # Menambahkan sampel sintetis ke array
#             synthetic_samples.append(synthetic_sample)
    
#     # Mengubah array numpy ke DataFrame
#     embedding_array = np.vstack(synthetic_samples)
#     embedding_df = pd.DataFrame(embedding_array, columns=['embedding'] * embedding_array.shape[1])
#     sarcasm_df = pd.DataFrame(np.zeros((embedding_array.shape[0], 1)), columns=['Sarcasm'])
#     synthetic_df = pd.concat([embedding_df, sarcasm_df], axis=1)
    
#     # Menambahkan label kelas minoritas pada data sintetis
#     synthetic_df['Sarcasm'] = 1

#     return synthetic_df

In [ ]:
# oversampled_df = SMOTE(df_ready, k=5, oversampling_ratio=1.0)

<h1>Training Bi-LSTM<h1>

In [36]:
# Bi-LSTM Algorithm

import numpy as np
import pickle as pkl

# activation function sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Turunan activation function sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# activation function tanh
def tanh(x):
    return np.tanh(x)

# Turunan activation function tanh
def tanh_derivative(x):
    return 1 - x**2

class BiLSTM:
    # Constructor
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Parameter untuk Input Gate Menggunakan Metode Xavier
        self.W_i = np.random.uniform(-1, 1, (hidden_size, input_size)) * np.sqrt(1 / input_size)
        self.U_i = np.random.uniform(-1, 1, (hidden_size, hidden_size)) * np.sqrt(1 / hidden_size)
        self.b_i = np.zeros((hidden_size, 1))
        
        # Parameter untuk Forget Gate Menggunakan Metode Xavier
        self.W_f = np.random.uniform(-1, 1, (hidden_size, input_size)) * np.sqrt(1 / input_size)
        self.U_f = np.random.uniform(-1, 1, (hidden_size, hidden_size)) * np.sqrt(1 / hidden_size)
        self.b_f = np.zeros((hidden_size, 1))
        
        # Parameter untuk Output Gate Menggunakan Metode Xavier
        self.W_o = np.random.uniform(-1, 1, (hidden_size, input_size)) * np.sqrt(1 / input_size)
        self.U_o = np.random.uniform(-1, 1, (hidden_size, hidden_size)) * np.sqrt(1 / hidden_size)
        self.b_o = np.zeros((hidden_size, 1))
        
        # Parameter untuk Cell State Menggunakan Metode Xavier
        self.W_c = np.random.uniform(-1, 1, (hidden_size, input_size)) * np.sqrt(1 / input_size)
        self.U_c = np.random.uniform(-1, 1, (hidden_size, hidden_size)) * np.sqrt(1 / hidden_size)
        self.b_c = np.zeros((hidden_size, 1))
        
        # Parameter untuk output layer Menggunakan Metode Xavier
        self.W_y = np.random.uniform(-1, 1, (output_size, hidden_size*2)) * np.sqrt(1 / (hidden_size*2))
        self.b_y = np.zeros((output_size, 1))

        self.count = 0
        
    def forward_backward(self, x):
        T = len(x)
        # print(T)
        self.count += 1

        self.h_forward = np.zeros((T + 1, self.hidden_size))
        self.c_forward = np.zeros((T + 1, self.hidden_size))
        self.h_backward = np.zeros((T + 1, self.hidden_size))
        self.c_backward = np.zeros((T + 1, self.hidden_size))
        self.gates_forward = np.zeros((T, self.hidden_size*4, self.hidden_size))
        self.gates_backward = np.zeros((T, self.hidden_size*4, self.hidden_size))
        self.outputs = np.zeros((T, self.output_size))
        
        for t in range(T):
            # Forward
            self.gates_forward[t] = np.concatenate([
                sigmoid(self.W_i @ x[t] + self.U_i @ self.h_forward[t] + self.b_i),
                sigmoid(self.W_f @ x[t] + self.U_f @ self.h_forward[t] + self.b_f),
                sigmoid(self.W_o @ x[t] + self.U_o @ self.h_forward[t] + self.b_o),
                tanh(self.W_c @ x[t] + self.U_c @ self.h_forward[t] + self.b_c)
            ])
        
            # print(f'Forget Gate Forward Iterasi {self.count}: {sigmoid(self.W_f @ x[t] + self.U_f @ self.h_forward[t] + self.b_f)}\n')
            # print(f'Input Gate Forward Iterasi {self.count}: {sigmoid(self.W_i @ x[t] + self.U_i @ self.h_forward[t] + self.b_i)}\n')
            # print(f'Output Gate Forward Iterasi {self.count}: {sigmoid(self.W_o @ x[t] + self.U_o @ self.h_forward[t] + self.b_o)}\n')
            self.c_forward[t + 1] = self.gates_forward[t, 1] * self.c_forward[t] + self.gates_forward[t, 0] * self.gates_forward[t, 3]
            self.h_forward[t + 1] = self.gates_forward[t, 2] * tanh(self.c_forward[t + 1])

            # print(f'Cell State Forward Iterasi {self.count}: {self.gates_forward[t, 1] * self.c_forward[t] + self.gates_forward[t, 0] * self.gates_forward[t, 3]}\n')
            # print(f'Hidden State Forward Iterasi {self.count}: {self.gates_forward[t, 2] * tanh(self.c_forward[t + 1])}\n')

            # backward
            t_backward = T - t - 1
            self.gates_backward[t_backward] = np.concatenate([
                sigmoid(self.W_i @ x[t_backward] + self.U_i @ self.h_backward[t_backward] + self.b_i),
                sigmoid(self.W_f @ x[t_backward] + self.U_f @ self.h_backward[t_backward] + self.b_f),
                sigmoid(self.W_o @ x[t_backward] + self.U_o @ self.h_backward[t_backward] + self.b_o),
                tanh(self.W_c @ x[t_backward] + self.U_c @ self.h_backward[t_backward] + self.b_c)
            ])
            
            # print(f'Forget Gate Backward Iterasi {self.count}: {sigmoid(self.W_f @ x[t_backward] + self.U_f @ self.h_backward[t_backward] + self.b_f)}\n')
            # print(f'Input Gate Backward Iterasi {self.count}: {sigmoid(self.W_i @ x[t_backward] + self.U_i @ self.h_backward[t_backward] + self.b_i)}\n')
            # print(f'Output Gate Backward Iterasi {self.count}: {sigmoid(self.W_o @ x[t_backward] + self.U_o @ self.h_backward[t_backward] + self.b_o)}\n')
            self.c_backward[t_backward + 1] = self.gates_backward[t_backward, 1] * self.c_backward[t_backward] + self.gates_backward[t_backward, 0] * self.gates_backward[t_backward, 3]
            self.h_backward[t_backward + 1] = self.gates_backward[t_backward, 2] * tanh(self.c_backward[t_backward + 1])

            # print(f'Cell State Backward Iterasi {self.count}: {self.gates_backward[t_backward, 1] * self.c_backward[t_backward] + self.gates_backward[t_backward, 0] * self.gates_backward[t_backward, 3]}\n')
            # print(f'Hidden State Backward Iterasi {self.count}: {self.gates_backward[t_backward, 2] * tanh(self.c_backward[t_backward + 1])}\n')

            # Merged Forward and Backward LSTM
            merged_output = np.concatenate([self.h_forward[t + 1], self.h_backward[t_backward + 1]])
            # h_reshaped = np.reshape(merged_output, (self.hidden_size*2,))
            # print(f'Final Output Reshape: {h_reshaped}\n')
            sigmoids = sigmoid(self.W_y @ merged_output + self.b_y)
            # print(f'Sigmoids: {sigmoids.shape}\n')
            self.outputs[t] = sigmoids[0]
        # print(f'Merged Output: {merged_output}\n')
        # print(f'final Outputs{self.outputs}\n')
        
        return self.outputs
    
    def backPropagation(self, x, y, learning_rate):
        T = len(x)
        dW_i, dU_i, db_i = np.zeros_like(self.W_i), np.zeros_like(self.U_i), np.zeros_like(self.b_i)
        dW_f, dU_f, db_f = np.zeros_like(self.W_f), np.zeros_like(self.U_f), np.zeros_like(self.b_f)
        dW_o, dU_o, db_o = np.zeros_like(self.W_o), np.zeros_like(self.U_o), np.zeros_like(self.b_o)
        dW_c, dU_c, db_c = np.zeros_like(self.W_c), np.zeros_like(self.U_c), np.zeros_like(self.b_c)
        dW_y, db_y = np.zeros_like(self.W_y), np.zeros_like(self.b_y)
        dc_next = np.zeros((1, self.hidden_size))
        dh_next = np.zeros((1, self.hidden_size))
        
        for t in reversed(range(T)):
            dy = self.outputs[t]
            # print(f'Outputs: {dy}\n')
            # print(f'{y[t]}\n')
            dy[y[t]] -= 1
            # print(f'Outputs minus 1{dy}\n')
            dy_transpose = dy.reshape(1, -1).T
            # print(f'Shape dy_transpose: {dy_transpose.shape}\n')
            # print(f'Shape self.W_y.T : {self.W_y.shape}\n')
            dh_forward = self.W_y.T @ dy_transpose + dh_next
            # print(f'Shape dh_forward: {dh_forward.shape}\n')
            dc_forward = dh_forward * self.gates_forward[t, 2] * tanh_derivative(tanh(self.c_forward[t + 1])) + dc_next
            dh_backward = self.W_y.T @ dy_transpose + dh_next
            dc_backward = dh_backward * self.gates_backward[t, 2] * tanh_derivative(tanh(self.c_backward[t + 1])) + dc_next
            
            # print(f'Shape dy_transpose: {dy_transpose.shape}\n')
            # print(f'Shape dW_y: {dW_y.shape}\n')
            # print(f'Shape self.h_forward: {self.h_forward[t + 1].shape}\n')
            # dW_y += dy_transpose @ np.expand_dims(self.h_forward[t + 1], axis=0) + dy_transpose @ np.expand_dims(self.h_backward[t + 1], axis=0) # Salah
            dW_y += dy_transpose @ np.expand_dims(np.concatenate([self.h_forward[t + 1], self.h_backward[t + 1][:self.hidden_size]]), axis=0) # Benar
            db_y += dy_transpose
            
            # print(f'dc_forward: {dc_forward.shape}, self.gates_forward[t, 3]: {self.gates_forward[t, 3].shape}\n')
            dg_forward = dc_forward * self.gates_forward[t, 2] * tanh_derivative(self.gates_forward[t, 3])
            dg_backward = dc_backward * self.gates_backward[t, 3]

            dgates_forward = self.gates_forward[t]
            # print(f'Shape dgates_forward[3]: {dgates_forward.shape}\n')
            # dg_forward_expanded = np.expand_dims(dg_forward, axis=0)
            dgated = dg_forward * tanh_derivative(dgates_forward[3])
            # print(f'tanh_derivative Shape: {dgated.shape}\n')
            # print(f'Shape dg_forward : {dg_forward.shape}')
            dgates_forward[3][:self.hidden_size] = np.sum(dg_forward[:self.hidden_size] * tanh_derivative(dgates_forward[3])[:self.hidden_size], axis=1) # Error disini
            dgates_forward[0][:self.hidden_size] = np.sum(dc_forward[:self.hidden_size] * self.gates_forward[t, 0], axis=1)
            dgates_forward[1][:self.hidden_size] = np.sum(dc_forward[:self.hidden_size] * self.c_forward[t], axis=1)
            dgates_forward[2][:self.hidden_size] = np.sum(dh_forward[:self.hidden_size] * tanh(self.c_forward[t + 1]) * sigmoid_derivative(dgates_forward[2]), axis=1)

            dgates_backward = self.gates_backward[t]
            dgates_backward[3][:self.hidden_size] = np.sum(dg_backward[:self.hidden_size] * tanh_derivative(dgates_backward[3]))
            dgates_backward[0][:self.hidden_size] = np.sum(dc_backward[:self.hidden_size] * self.gates_backward[t, 0])
            dgates_backward[1][:self.hidden_size] = np.sum(dc_backward[:self.hidden_size] * self.c_backward[t])
            dgates_backward[2][:self.hidden_size] = np.sum(dh_backward[:self.hidden_size] * tanh(self.c_backward[t + 1]) * sigmoid_derivative(dgates_backward[2]))
            
            x_transpose = np.array([x[t]])
            dgates_transpose_forward_0 = np.array([dgates_forward[0]])
            dgates_transpose_forward_1 = np.array([dgates_forward[1]])
            dgates_transpose_forward_2 = np.array([dgates_forward[2]])
            dgates_transpose_forward_3 = np.array([dgates_forward[3]])

            dgates_transpose_backward_0 = np.array([dgates_backward[0]])
            dgates_transpose_backward_1 = np.array([dgates_backward[1]])
            dgates_transpose_backward_2 = np.array([dgates_backward[2]])
            dgates_transpose_backward_3 = np.array([dgates_backward[3]])
            
            dW_i += dgates_transpose_forward_0.T @ x_transpose + dgates_transpose_backward_0.T @ x_transpose
            dU_i += dgates_forward[0] @ self.h_forward[t].T + dgates_backward[0] @ self.h_backward[t].T
            db_i += dgates_transpose_forward_0.T + dgates_transpose_backward_0.T
            
            dW_f += dgates_transpose_forward_1.T @ x_transpose + dgates_transpose_backward_1.T @ x_transpose # Error disini
            dU_f += dgates_forward[1] @ self.h_forward[t].T + dgates_backward[1] @ self.h_backward[t].T
            db_f += dgates_transpose_forward_1.T + dgates_transpose_backward_1.T
            
            dW_o += dgates_transpose_forward_2.T @ x_transpose + dgates_transpose_backward_2.T @ x_transpose
            dU_o += dgates_forward[2] @ self.h_forward[t].T + dgates_backward[2] @ self.h_backward[t].T
            db_o += dgates_transpose_forward_2.T + dgates_transpose_backward_2.T
            
            dW_c += dgates_transpose_forward_3.T @ x_transpose + dgates_transpose_backward_3.T @ x_transpose
            dU_c += dgates_forward[3] @ self.h_forward[t].T + dgates_backward[3] @ self.h_backward[t].T
            db_c += dgates_transpose_forward_3.T + dgates_transpose_backward_3.T
            
            dh_next = self.U_i.T @ dgates_forward[0] + self.U_f.T @ dgates_forward[1] + self.U_o.T @ dgates_forward[2] + self.U_c.T @ dgates_forward[3]
            dc_next = dc_forward * self.gates_forward[t, 1]
        
        for param in [dW_i, dU_i, db_i, dW_f, dU_f, db_f, dW_o, dU_o, db_o, dW_c, dU_c, db_c, dW_y, db_y]:
            np.clip(param, -1, 1, out=param)
        
        self.W_i -= learning_rate * dW_i
        self.U_i -= learning_rate * dU_i
        self.b_i -= learning_rate * db_i
        
        self.W_f -= learning_rate * dW_f
        self.U_f -= learning_rate * dU_f
        self.b_f -= learning_rate * db_f
        
        self.W_o -= learning_rate * dW_o
        self.U_o -= learning_rate * dU_o
        self.b_o -= learning_rate * db_o
        
        self.W_c -= learning_rate * dW_c
        self.U_c -= learning_rate * dU_c
        self.b_c -= learning_rate * db_c
        
        self.W_y -= learning_rate * dW_y
        self.b_y -= learning_rate * db_y
    
    def train(self, x, y, epochs, learning_rate):
        for epoch in range(epochs):
            outputs = self.forward_backward(x)
            self.backPropagation(x, y, learning_rate)
            # print(f'Hasil Prediksi {outputs}')
            outputs = np.clip(outputs, 1e-15, None)
            loss = -np.mean(np.log(outputs[np.arange(len(y)), y]))
            
            print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}')
    
    def predict(self, x):
        T = len(x)
        h_forward = np.zeros((T + 1, self.hidden_size))
        c_forward = np.zeros((T + 1, self.hidden_size))
        h_backward = np.zeros((T + 1, self.hidden_size))
        c_backward = np.zeros((T + 1, self.hidden_size))
        outputs = np.zeros((T, self.output_size))
        
        for t in range(T):
            # Forward
            gates_forward = np.concatenate([
                sigmoid(self.W_i @ x[t] + self.U_i @ h_forward[t] + self.b_i),
                sigmoid(self.W_f @ x[t] + self.U_f @ h_forward[t] + self.b_f),
                sigmoid(self.W_o @ x[t] + self.U_o @ h_forward[t] + self.b_o),
                tanh(self.W_c @ x[t] + self.U_c @ h_forward[t] + self.b_c)
            ])
                
            c_forward[t + 1] = gates_forward[1] * c_forward[t] + gates_forward[0] * gates_forward[3]
            h_forward[t + 1] = gates_forward[2] * tanh(c_forward[t + 1])
                
            # Backward
            t_backward = T - t - 1
            gates_backward = np.concatenate([
                sigmoid(self.W_i @ x[t_backward] + self.U_i @ h_backward[t_backward] + self.b_i),
                sigmoid(self.W_f @ x[t_backward] + self.U_f @ h_backward[t_backward] + self.b_f),
                sigmoid(self.W_o @ x[t_backward] + self.U_o @ h_backward[t_backward] + self.b_o),
                tanh(self.W_c @ x[t_backward] + self.U_c @ h_backward[t_backward] + self.b_c)
            ])
                
            c_backward[t_backward + 1] = gates_backward[1] * c_backward[t_backward] + gates_backward[0] * gates_backward[3]
            h_backward[t_backward + 1] = gates_backward[2] * tanh(c_backward[t_backward + 1])

            merged_output = np.concatenate([h_forward[t + 1], h_backward[t_backward + 1]])
            sigmoids = sigmoid(self.W_y @ merged_output + self.b_y)
            outputs[t] = sigmoids[0]
        
        return np.argmax(outputs, axis=1)
    
    def save_model(self, model, filename):
        with open(filename, 'wb') as f:
            pkl.dump(model, f)

<h2>Training & Testing Model</h2>

<pre>
Percobaan 1 :
embedding size = 50
max_len = 25
hidden_size = 1

Percobaan 2 :
embedding size = 25
max_len = 25
hidden_size = 2

Percobaan 3:
Menambahkan value dari fitur sentiment pada data Training
</pre>

In [37]:
import numpy as np

In [38]:
y_oversampled

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

<p>Bi-LSTM</p>

In [39]:
x_train = X_oversampled
x_train = np.array(x_train)
# label = final_stack_label.astype('int')
y_trains = y_oversampled

# Inisialisasi model Bi-LSTM
input_size = x_train.shape[1]
hidden_size = 7
output_size = 2
bilstm = BiLSTM(input_size, hidden_size, output_size)

In [ ]:
x_train.shape

In [ ]:
y_trains.shape

In [40]:
# Train ML Model
epochs = 150
learning_rate = 0.001
bilstm.train(x_train, y_trains, epochs, learning_rate)

Epoch 1/150, Loss: 34.5388
Epoch 2/150, Loss: 34.5388
Epoch 3/150, Loss: 34.5388
Epoch 4/150, Loss: 34.5388
Epoch 5/150, Loss: 34.5388
Epoch 6/150, Loss: 34.5388
Epoch 7/150, Loss: 34.5388
Epoch 8/150, Loss: 34.5388
Epoch 9/150, Loss: 34.5388
Epoch 10/150, Loss: 34.5388
Epoch 11/150, Loss: 34.5388
Epoch 12/150, Loss: 34.5388
Epoch 13/150, Loss: 34.5388
Epoch 14/150, Loss: 34.5388
Epoch 15/150, Loss: 34.5388
Epoch 16/150, Loss: 34.5388
Epoch 17/150, Loss: 34.5388
Epoch 18/150, Loss: 34.5388
Epoch 19/150, Loss: 34.5388
Epoch 20/150, Loss: 34.5388
Epoch 21/150, Loss: 34.5388
Epoch 22/150, Loss: 34.5388
Epoch 23/150, Loss: 34.5388
Epoch 24/150, Loss: 34.5388
Epoch 25/150, Loss: 34.5388
Epoch 26/150, Loss: 34.5388
Epoch 27/150, Loss: 34.5388
Epoch 28/150, Loss: 34.5388
Epoch 29/150, Loss: 34.5388
Epoch 30/150, Loss: 34.5388
Epoch 31/150, Loss: 34.5388
Epoch 32/150, Loss: 34.5388
Epoch 33/150, Loss: 34.5388
Epoch 34/150, Loss: 34.5388
Epoch 35/150, Loss: 34.5388
Epoch 36/150, Loss: 34.5388
E

In [41]:
X_test_embedding_r.shape

(439, 3900)

In [42]:
X_test_embedding_r[1]

array([-0.04268292,  0.14066966,  0.20659287, ...,  0.02416898,
        0.06397357, -0.03179826])

In [43]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,

In [44]:
# Predict
output_predict = []
for i in range(len(X_test_embedding_r)):
    output_predict.append(bilstm.predict(np.array([X_test_embedding_r[i]])))

In [45]:
output_predict

[array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], 

In [46]:
df_result = pd.DataFrame.from_records(output_predict, columns=['Predict'])

In [47]:
df_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Predict  439 non-null    int64
dtypes: int64(1)
memory usage: 3.6 KB


In [48]:
output_actual = []

for i in y_test:
    output_actual.append(i)

In [49]:
df_actual = pd.DataFrame(output_actual, columns=['Actual'])

In [50]:
df_final_result = df_result.join(df_actual)

In [51]:
df_final_result.head(11)

Predict  Actual
0         0       0
1         0       1
2         0       0
3         0       1
4         0       1
5         0       1
6         0       1
7         0       0
8         0       1
9         0       0
10        0       0

In [52]:
for i in range(len(df_final_result)):
  if (df_final_result.iloc[i]['Predict'] == 1 and df_final_result.iloc[i]['Actual'] == 1):
    df_final_result.loc[i, 'Category'] = 'TP'
  elif (df_final_result.iloc[i]['Predict'] == 0 and df_final_result.iloc[i]['Actual'] == 0):
    df_final_result.loc[i, 'Category'] = 'TN'
  elif (df_final_result.iloc[i]['Predict'] == 1 and df_final_result.iloc[i]['Actual'] == 0):
    df_final_result.loc[i, 'Category'] = 'FP'
  elif (df_final_result.iloc[i]['Predict'] == 0 and df_final_result.iloc[i]['Actual'] == 1):
    df_final_result.loc[i, 'Category'] = 'FN'

In [53]:
TP = len(df_final_result[df_final_result['Category']=='TP'])
TN = len(df_final_result[df_final_result['Category']=='TN'])
FP = len(df_final_result[df_final_result['Category']=='FP'])
FN = len(df_final_result[df_final_result['Category']=='FN'])

accuracy = round((TP + TN) / (TP + TN + FP + FN), 2)

In [54]:
print(f'Accuracy: {accuracy * 100}%')

Accuracy: 56.99999999999999%


<h3>Testing Result</h3>
<p>July 20 : 50%</p>
<p>July 21 : 53%</p>
<p>July 22 : 54%</p>
<p>July 25 : 61%</p>

<h1>Sample Datasets BAB 3</h1>

In [ ]:
df_bab3 = pd.read_excel('Misc/Sample_Datasets_Bab3_Ready.xlsx')
df_bab3.info()
df_bab3.head()

In [ ]:
# Remove unused column/feature
df_bab3 = df_bab3.drop(columns='Unnamed: 0')
df_bab3 = df_bab3.drop(columns='Text')
df_bab3 = df_bab3.drop(columns='emoji')
df_bab3 = df_bab3.drop(columns='Tokenized')
df_bab3 = df_bab3.drop(columns='final_text')
df_bab3 = df_bab3.drop(columns='Pos_Word')
df_bab3 = df_bab3.drop(columns='Neg_Word')
df_bab3 = df_bab3.drop(columns='Total_Word')
df_bab3 = df_bab3.drop(columns='Pos_Ratio')
df_bab3 = df_bab3.drop(columns='Neg_Ratio')
df_bab3 = df_bab3.drop(columns='Tokenize_Emoji')
df_bab3 = df_bab3.drop(columns='Pos_Emoji')
df_bab3 = df_bab3.drop(columns='Neg_Emoji')
df_bab3 = df_bab3.drop(columns='Sentimen_Emoji')

In [ ]:
df_bab3['Sarcasm'].value_counts()

In [ ]:
df_bab3['text_emoji'][0]

<h2>Word Embedding</h2>

In [ ]:
# Membangun model GloVe
glove_model = GloVe(df_bab3['text_emoji'])

# Membangun vocabulary
glove_model.build_vocab_information()

# Membangun co-occurrence matrix
glove_model.build_co_matrix()

# Melatih model GloVe
glove_model.train()

In [ ]:
for word, id in glove_model.word2count.items():
    print(f'{word}: {id}')

In [ ]:
# glove_model.generate_coomatrix_image()

In [ ]:
glove_model.get_all_embeddings()

<h2>SMOTE</h2>

In [ ]:
df_bab3['Sentimen_Text'] = df_bab3['Sentimen_Text'].replace('Positif', 1)
df_bab3['Sentimen_Text'] = df_bab3['Sentimen_Text'].replace('Negatif', 0)

df_bab3['Sarcasm'] = df_bab3['Sarcasm'].replace('Positif', 1)
df_bab3['Sarcasm'] = df_bab3['Sarcasm'].replace('Negatif', 0)

In [ ]:
# Cek class minoritas
df_bab3['Sarcasm'].value_counts()

In [ ]:
max_len = 50
len_voc = 40000

from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df_bab3, test_size=0.3, random_state=42, shuffle=False)

df_train_min = df_train[df_train['Sarcasm'] == 0]
df_train_maj = df_train[df_train['Sarcasm'] == 1]

df_test_min = df_test[df_test['Sarcasm'] == 0]
df_test_maj = df_test[df_test['Sarcasm'] == 1]

df_ready_min = pd.concat([df_train_min, df_test_min])
df_ready_maj = pd.concat([df_train_maj, df_test_maj])

In [ ]:
# Tokenizer
tokenizer_min = make_tokenizer(df_ready_min['text_emoji'], len_voc)
tokenizer_maj = make_tokenizer(df_ready_maj['text_emoji'], len_voc)

In [ ]:
# Sequence
X_train_min = tokenizer_min.texts_to_sequences(df_train_min['text_emoji'])
X_test_min = tokenizer_min.texts_to_sequences(df_test_min['text_emoji'])
X_train_major = tokenizer_maj.texts_to_sequences(df_train_maj['text_emoji'])
X_test_major = tokenizer_maj.texts_to_sequences(df_test_maj['text_emoji'])

In [ ]:
df_train_min

In [ ]:
X_train_min

In [ ]:
# Padding
from keras.utils import pad_sequences

X_train_min = pad_sequences(X_train_min, maxlen=max_len, padding='post', truncating='post')
X_test_min = pad_sequences(X_test_min, maxlen=max_len, padding='post', truncating='post')
X_train_major = pad_sequences(X_train_major, maxlen=max_len, padding='post', truncating='post')
X_test_major = pad_sequences(X_test_major, maxlen=max_len, padding='post', truncating='post')

In [ ]:
# Stacking Label Minority
y_train_min = df_train_min['Sarcasm'].values
y_test_min = df_test_min['Sarcasm'].values

stack_label_min = np.hstack((y_train_min, y_test_min))

stack_label_min.shape

In [ ]:
# Stacking Label Majority
y_train_maj = df_train_maj['Sarcasm'].values
y_test_maj = df_test_maj['Sarcasm'].values

stack_label_maj = np.hstack((y_train_maj, y_test_maj))

stack_label_maj.shape

In [ ]:
# Stacking All Data Minority & Majority
embed_mat_min = make_embedding_matrix(glove, tokenizer_min, len_voc)
embed_mat_maj = make_embedding_matrix(glove, tokenizer_maj, len_voc)

X_train_emb_minority = embed_mat_min[X_train_min]
X_test_emb_minority = embed_mat_min[X_test_min]

X_train_emb_majority = embed_mat_maj[X_train_major]
X_test_emb_majority = embed_mat_maj[X_test_major]

train_size_min, max_len_min, embed_size_min = X_train_emb_minority.shape
X_train_emb_r_min = X_train_emb_minority.reshape(train_size_min, max_len*embed_size_min)

test_size_min, max_len_min, embed_size_min = X_test_emb_minority.shape
X_test_emb_r_min = X_test_emb_minority.reshape(test_size_min, max_len*embed_size_min)

train_size_maj, max_len_maj, embed_size_maj = X_train_emb_majority.shape
X_train_emb_r_maj = X_train_emb_majority.reshape(train_size_maj, max_len*embed_size_maj)

test_size_maj, max_len_maj, embed_size_maj = X_test_emb_majority.shape
X_test_emb_r_maj = X_test_emb_majority.reshape(test_size_maj, max_len*embed_size_maj)

stack_minority = np.vstack((X_train_emb_r_min, X_test_emb_r_min))

stack_majority = np.vstack((X_train_emb_r_maj, X_test_emb_r_maj))

In [ ]:
X_train_emb_minority[1]

In [ ]:
print(f'Shape stack minority: {stack_minority.shape}')
print(f'Shape stack majority{stack_majority.shape}')

In [ ]:
# Running SMOTE
total_size = train_size_maj + train_size_min + test_size_maj + test_size_min

X_minority = stack_minority
y_minority = stack_label_min
X_majority = stack_majority
y_majority = stack_label_maj

X_oversampled, y_oversampled = smote(X_minority, X_majority, y_minority, k=3)

In [ ]:
final_stack = np.vstack((stack_majority, X_oversampled))

len(final_stack)

In [ ]:
final_stack = np.delete(final_stack, np.s_[10::], axis=0)

In [ ]:
final_stack_label = np.hstack((stack_label_maj, y_oversampled))

final_stack_label = np.delete(final_stack_label, np.s_[10::], axis=0)

In [ ]:
print(f'Shape : {final_stack.shape}\n')
print(final_stack)

In [ ]:
import matplotlib.pyplot as plt

x = ['Sebelum', 'Sesudah']
y = [len(stack_majority) + len(stack_minority), len(final_stack)]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Perbandingan Data Setelah Diimplementasi SMOTE')

plt.show()

In [ ]:
x = ['0', '1']
y = [df_bab3['Sarcasm'].value_counts()[0], df_bab3['Sarcasm'].value_counts()[1]]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Jumlah Sample Masing-Masing Kelas Sebelum Di Implementasi SMOTE')

plt.show()

In [ ]:
# Menghitung Jumlah Akhir Sample pada Class 0 dan 1
unique, counts = np.unique(final_stack_label, return_counts=True)
result = np.asarray((unique, counts)).T.astype(int)

print(result)

In [ ]:
x = ['0', '1']
y = [result[0][1], result[1][1]]


plt.bar(x, y, color=[(0.38, 0.62, 0.79), (0.98, 0.64, 0.33)], edgecolor='black', linewidth=1.5)

for i in range(len(x)):
    plt.text(x[i], y[i], str(y[i]), ha='center', va='bottom')

plt.ylabel('Jumlah Sample')
plt.title('Jumlah Sample Masing-Masing Kelas Setelah Di Implementasi SMOTE')

plt.show()

<h2>Bi-LSTM</h2>

In [ ]:
x_train = final_stack
x_train = np.array(x_train)
label = final_stack_label.astype('int')
y_train = label

# Inisialisasi model Bi-LSTM
input_size = x_train.shape[1]
hidden_size = 8
output_size = 2
bilstm = BiLSTM(input_size, hidden_size, output_size)

In [ ]:
x_train

In [ ]:
# Train ML Model
epochs = 100
learning_rate = 0.01
bilstm.train(x_train, y_train, epochs, learning_rate)

In [ ]:
y_train

In [ ]:
x_train[9]

In [ ]:
# Predict ML Model
print(f'Predict Data 1 : {bilstm.predict(np.array([x_train[0]]))}\n')
print(f'Predict Data 2 : {bilstm.predict(np.array([x_train[1]]))}\n')
print(f'Predict Data 3 : {bilstm.predict(np.array([x_train[2]]))}\n')
print(f'Predict Data 4 : {bilstm.predict(np.array([x_train[3]]))}\n')
print(f'Predict Data 5 : {bilstm.predict(np.array([x_train[4]]))}\n')
print(f'Predict Data 6 : {bilstm.predict(np.array([x_train[5]]))}\n')
print(f'Predict Data 7 : {bilstm.predict(np.array([x_train[6]]))}\n')
print(f'Predict Data 8 : {bilstm.predict(np.array([x_train[7]]))}\n')
print(f'Predict Data 9 : {bilstm.predict(np.array([x_train[8]]))}\n')
print(f'Predict Data 10 : {bilstm.predict(np.array([x_train[9]]))}\n')